### ISSUE TITLE
Integration with futures crate

### ISSUE THREAD

**Issue by svenknobloch** [austinjones/postage-rs#36]
Would it be possible to add support for the `Stream`/`Sink` traits from the `futures` crate?

AFAIK it's the most popular crate for those traits and would allow for use of all the additional combinators that `futures` already provides.

**Comment by austinjones** [comment]
Yeah, I think I could implement those traits for the postage channels.

**Comment by austinjones** [comment]
Thanks for submitting this!  Seems like it would make it a lot easier to use postage in existing codebases that are futures-based. 👍🏻

**Comment by austinjones** [comment]
I was able to implement this for all Senders/Receivers.  I'll push v0.4.1 in a bit with the code.

I couldn't implement Sink for the broadcast Sender though.  The postage Sink trait takes the Context and Item at the same time (whereas the futures trait provides them in two separate calls).  The broadcast channel really depends on this behavior.
