### ISSUE TITLE
Dropping a oneshot sender does not wake the receiver

### ISSUE THREAD

**Issue by maxbrunsfeld** [austinjones/postage-rs#44]
With `mpsc` channels, if I drop all the senders, any outstanding `recv` calls will return an error. But with `oneshot` channels, this doesn't seem to happen; when I drop the sender, an outstanding `recv` call will just hang. Is it intentional that the behavior of `oneshot` channels differs from `mpsc` channels in this regard?

**Comment by austinjones** [comment]
Thanks for the report!  This is fixed in v0.5.0 and is up on crates.io.

**Comment by maxbrunsfeld** [comment]
Awesome, thank you!
