### ISSUE TITLE
Use parking_lot for synchronization

### ISSUE THREAD

**Issue by loafofpiecrust** [austinjones/postage-rs#47]
I use [`parking_lot`](https://github.com/Amanieu/parking_lot) for synchronization primitives and it's fantastic compared to `std`: faster, smaller, and locks don't poison (so you don't need `.unwrap()` or `.expect()` on lock functions). I suspect this would bring performance closer to tokio, especially since I think they'll beat tokio's async `RwLock` since you don't need to use it across an await boundary.

**Comment by austinjones** [comment]
Thanks for the idea!  I've implemented it and it will be going out in v0.5.0 soon.
